import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFile, unlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import type { TemporalBacktestResult } from "../lib/elo/backtest";

const analyticalSections = [
  "dataQuality",
  "split",
  "methodology",
  "evaluationContext",
  "references",
  "evaluatedModelExamples",
  "experiments",
  "selection",
  "finalModels",
  "conclusion",
  "limitations",
] as const satisfies ReadonlyArray<keyof TemporalBacktestResult>;

const stableManifestFields = [
  "dataSha256",
  "configSha256",
  "sourceSnapshotSha256",
  "sourceSnapshotFileSha256",
  "sourceSnapshotExportedAt",
  "evaluatedModelVersion",
  "sourceCodeSha256",
  "sourceFiles",
  "sourceExtraction",
  "acceptedRows",
  "earliestCompletedAt",
  "latestCompletedAt",
] as const satisfies ReadonlyArray<keyof TemporalBacktestResult["manifest"]>;

async function readReport(file: string): Promise<TemporalBacktestResult> {
  return JSON.parse(await readFile(file, "utf8")) as TemporalBacktestResult;
}

async function main() {
  const checkedInPath = path.resolve("public/data/elo-backtest.json");
  const replayPath = path.join(
    tmpdir(),
    `valomapped-backtest-verify-${process.pid}-${Date.now()}.json`
  );

  try {
    execFileSync(
      process.execPath,
      [
        path.resolve("node_modules/tsx/dist/cli.mjs"),
        path.resolve("scripts/run-elo-backtest.ts"),
        "--source=snapshot",
        "--input=data/elo-backtest-db-snapshot.json",
        `--output=${replayPath}`,
      ],
      { cwd: process.cwd(), encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }
    );

    const [checkedIn, replay] = await Promise.all([
      readReport(checkedInPath),
      readReport(replayPath),
    ]);

    assert.equal(
      checkedIn.manifest.source,
      "snapshot",
      "The published artifact must be generated by the offline snapshot replay."
    );
    assert.equal(checkedIn.schemaVersion, replay.schemaVersion, "Schema version drifted.");
    assert.equal(
      checkedIn.implementationVersion,
      replay.implementationVersion,
      "Implementation version drifted."
    );

    for (const field of stableManifestFields) {
      assert.deepEqual(
        checkedIn.manifest[field],
        replay.manifest[field],
        `Manifest field ${field} does not match a fresh replay.`
      );
    }

    for (const section of analyticalSections) {
      assert.deepEqual(
        checkedIn[section],
        replay[section],
        `Analytical section ${section} does not match a fresh replay.`
      );
    }

    console.log(
      "Backtest artifact verification passed: snapshot, source/config provenance, and analytical sections match a fresh offline replay."
    );
  } finally {
    await unlink(replayPath).catch(() => undefined);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack ?? error.message : error);
  process.exitCode = 1;
});
