import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFile, unlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  stableStringify,
  type TemporalSplitConfig,
} from "../lib/elo/backtest";
import type { PickBanTemporalBacktestResult } from "../lib/elo/pick-ban-backtest";

const EXPECTED_SNAPSHOT_SCHEMA_VERSION = "1.2.0";
const EXPECTED_DB_QUERY_VERSION = "pick-ban-veto-maps-ratings-v2";
const EXPECTED_RATING_HISTORY_MODEL_VERSION = "unknown-unversioned";

interface PickBanBacktestManifest {
  generatedAt: string;
  source: "snapshot" | "db";
  dataSha256: string;
  configSha256: string;
  sourceDescriptor: string;
  sourceSnapshotSha256: string;
  sourceSnapshotFileSha256: string | null;
  sourceSnapshotExportedAt: string | null;
  databaseQueryVersion: string;
  ratingHistoryModelVersion: "unknown-unversioned";
  sourceCodeSha256: string;
  sourceFiles: string[];
  gitCommit: string | null;
  gitWorkingTree: "clean" | "dirty" | "unknown";
  provenanceCapturedAt: string;
  provenanceCapturePoint: "before input reads and artifact writes";
  sourceExtraction: unknown;
  configuration: {
    split: TemporalSplitConfig;
    bootstrapIterations: number;
    bootstrapSeed: number;
  };
  inputCounts: {
    matches: number;
    eloRatings: number;
  };
  inputObservedRange: {
    earliestMatchAt: string | null;
    latestMatchAt: string | null;
  };
  acceptedMatches: number;
}

type PublishedPickBanBacktest = PickBanTemporalBacktestResult & {
  manifest: PickBanBacktestManifest;
};

async function readReport(file: string): Promise<PublishedPickBanBacktest> {
  return JSON.parse(await readFile(file, "utf8")) as PublishedPickBanBacktest;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function assertCurrentSnapshot(snapshotPath: string): Promise<void> {
  const snapshot = JSON.parse(await readFile(snapshotPath, "utf8")) as unknown;
  assert.ok(isRecord(snapshot), "Snapshot must be a JSON object.");
  assert.equal(
    snapshot.schemaVersion,
    EXPECTED_SNAPSHOT_SCHEMA_VERSION,
    "Snapshot schema version is not current."
  );
  assert.equal(
    snapshot.queryVersion,
    EXPECTED_DB_QUERY_VERSION,
    "Snapshot database query version is not current."
  );
  assert.ok(isRecord(snapshot.extraction), "Snapshot extraction metadata is missing.");
  assert.ok(
    isRecord(snapshot.extraction.database),
    "Snapshot database transaction metadata is missing."
  );
  assert.ok(
    isRecord(snapshot.extraction.sourceQuality),
    "Snapshot source-quality metadata is missing."
  );
  assert.equal(
    snapshot.extraction.sourceQuality.sourceLessRatingsOutsideHardResetSignature,
    0,
    "Snapshot contains source-less ratings whose target-series provenance cannot be proven."
  );
  assert.equal(
    snapshot.extraction.sourceQuality.ratingsWithoutSourceMatchId,
    snapshot.extraction.sourceQuality.sourceLessRatingsMatchingHardResetSignature,
    "Every source-less snapshot rating must match the documented hard-reset signature."
  );
  assert.equal(
    snapshot.exportedAt,
    snapshot.extraction.database.transactionTimestampUtc,
    "Snapshot exportedAt must equal its database transaction timestamp."
  );
}

function canonicalReport(
  report: PublishedPickBanBacktest
): PublishedPickBanBacktest {
  const comparable = structuredClone(report);
  delete (comparable.manifest as Partial<PickBanBacktestManifest>).generatedAt;
  delete (comparable.manifest as Partial<PickBanBacktestManifest>).gitCommit;
  delete (comparable.manifest as Partial<PickBanBacktestManifest>).gitWorkingTree;
  delete (comparable.manifest as Partial<PickBanBacktestManifest>)
    .provenanceCapturedAt;
  return JSON.parse(stableStringify(comparable)) as PublishedPickBanBacktest;
}

async function main(): Promise<void> {
  const checkedInPath = path.resolve("public/data/pick-ban-backtest.json");
  const snapshotPath = path.resolve("data/pick-ban-backtest-db-snapshot.json");
  await assertCurrentSnapshot(snapshotPath);
  const checkedIn = await readReport(checkedInPath);
  assert.equal(
    checkedIn.manifest.source,
    "snapshot",
    "The published pick/ban artifact must be generated by the offline snapshot replay."
  );
  assert.equal(
    checkedIn.manifest.databaseQueryVersion,
    EXPECTED_DB_QUERY_VERSION,
    "Published artifact database query version is not current."
  );
  assert.equal(
    checkedIn.manifest.ratingHistoryModelVersion,
    EXPECTED_RATING_HISTORY_MODEL_VERSION,
    "Stored historical ratings must not claim a known model version."
  );

  const replayPath = path.join(
    tmpdir(),
    `valomapped-pick-ban-backtest-verify-${process.pid}-${Date.now()}.json`
  );
  const configuration = checkedIn.manifest.configuration;
  try {
    execFileSync(
      process.execPath,
      [
        path.resolve("node_modules/tsx/dist/cli.mjs"),
        path.resolve("scripts/run-pick-ban-backtest.ts"),
        "--source=snapshot",
        `--input=${snapshotPath}`,
        `--output=${replayPath}`,
        `--train-end=${configuration.split.trainEndExclusive}`,
        `--validation-end=${configuration.split.validationEndExclusive}`,
        `--test-end=${configuration.split.testEndExclusive ?? "none"}`,
        `--bootstrap-iterations=${configuration.bootstrapIterations}`,
        `--seed=${configuration.bootstrapSeed}`,
      ],
      {
        cwd: process.cwd(),
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      }
    );

    const replay = await readReport(replayPath);
    assert.deepEqual(
      canonicalReport(checkedIn),
      canonicalReport(replay),
      "Published pick/ban report does not match a fresh snapshot replay after removing only explicit volatile manifest fields."
    );

    console.log(
      "Pick/ban backtest verification passed: the entire canonical report matches a fresh offline snapshot replay."
    );
  } finally {
    await unlink(replayPath).catch(() => undefined);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack ?? error.message : error);
  process.exitCode = 1;
});
